document.getElementById('canaryMap').src=window.C8_MAP;
const islands={'la-palma':{name:'La Palma',x:6.5,y:43},'el-hierro':{name:'El Hierro',x:3.5,y:94},'la-gomera':{name:'La Gomera',x:20,y:74.3},'tenerife':{name:'Tenerife',x:34.8,y:64},'gran-canaria':{name:'Gran Canaria',x:54.1,y:83},'fuerteventura':{name:'Fuerteventura',x:86,y:58},'lanzarote':{name:'Lanzarote',x:95,y:21.5},'la-graciosa':{name:'La Graciosa',x:98.4,y:8.3}};
const people=[
{id:'benito-perez-galdos',name:'Benito Pérez Galdós',born:1843,island:'gran-canaria',category:'Literatura',role:'Novelista y dramaturgo',bio:'Una de las figuras centrales de la literatura española del siglo XIX. Nació en Las Palmas de Gran Canaria y su obra convirtió la vida social y política de su tiempo en materia literaria.'},
{id:'fernando-leon-castillo',name:'Fernando León y Castillo',born:1842,island:'gran-canaria',category:'Política',role:'Diplomático y político',bio:'Diplomático y político grancanario, figura destacada de la vida pública española de la segunda mitad del siglo XIX.'},
{id:'juan-negrin',name:'Juan Negrín López',born:1892,island:'gran-canaria',category:'Ciencia',role:'Médico, fisiólogo y político',bio:'Médico y fisiólogo nacido en Las Palmas de Gran Canaria, con una trayectoria científica y política de alcance internacional.'},
{id:'nestor',name:'Néstor Martín-Fernández de la Torre',born:1887,island:'gran-canaria',category:'Artes',role:'Pintor',bio:'Pintor grancanario vinculado al simbolismo y a una poderosa construcción estética de la identidad insular.'},
{id:'tomas-morales',name:'Tomás Morales Castellano',born:1884,island:'gran-canaria',category:'Literatura',role:'Poeta',bio:'Poeta modernista nacido en Moya, Gran Canaria, autor de una obra profundamente vinculada al Atlántico y al paisaje insular.'},
{id:'josefina-torre',name:'Josefina de la Torre',born:1907,island:'gran-canaria',category:'Literatura',role:'Poeta, actriz y cantante',bio:'Creadora polifacética nacida en Las Palmas de Gran Canaria, vinculada a la poesía, el teatro, el cine y la música.'},
{id:'alfredo-kraus',name:'Alfredo Kraus',born:1927,island:'gran-canaria',category:'Música',role:'Tenor',bio:'Tenor nacido en Las Palmas de Gran Canaria, reconocido internacionalmente por su técnica y su interpretación del repertorio lírico.'},
{id:'martin-chirino',name:'Martín Chirino',born:1925,island:'gran-canaria',category:'Artes',role:'Escultor',bio:'Escultor grancanario, referente de la abstracción española y autor de una obra marcada por el hierro, la espiral y la memoria atlántica.'},
{id:'manolo-millares',name:'Manolo Millares',born:1926,island:'gran-canaria',category:'Artes',role:'Pintor',bio:'Pintor nacido en Las Palmas de Gran Canaria y figura esencial del arte español de posguerra.'},
{id:'angel-guimera',name:'Ángel Guimerá',born:1845,island:'tenerife',category:'Literatura',role:'Dramaturgo y poeta',bio:'Dramaturgo y poeta nacido en Santa Cruz de Tenerife. Su trayectoria literaria lo convirtió en una de las figuras fundamentales del teatro de su época.'},
{id:'oscar-dominguez',name:'Óscar Domínguez',born:1906,island:'tenerife',category:'Artes',role:'Pintor surrealista',bio:'Pintor tinerfeño y una de las figuras canarias de mayor proyección dentro del surrealismo europeo.'},
{id:'maria-rosa-alonso',name:'María Rosa Alonso',born:1909,island:'tenerife',category:'Pensamiento',role:'Filóloga y ensayista',bio:'Filóloga, ensayista e investigadora tinerfeña, referente intelectual de la cultura canaria del siglo XX.'},
{id:'antonio-gonzalez',name:'Antonio González González',born:1917,island:'tenerife',category:'Ciencia',role:'Químico e investigador',bio:'Químico tinerfeño de gran relevancia científica, especialmente vinculado a la investigación de productos naturales.'},
{id:'luis-morera',name:'Luis Morera',born:1946,island:'la-palma',category:'Música',role:'Músico y artista',bio:'Músico y artista palmero con una trayectoria profundamente vinculada al paisaje, la identidad y la cultura de Canarias.'},
{id:'felix-casanova',name:'Félix Francisco Casanova',born:1956,island:'la-palma',category:'Literatura',role:'Poeta y escritor',bio:'Poeta y escritor nacido en Santa Cruz de La Palma, cuya breve e intensa obra ocupa un lugar singular en la literatura canaria contemporánea.'},
{id:'pedro-garcia-cabrera',name:'Pedro García Cabrera',born:1905,island:'la-gomera',category:'Literatura',role:'Poeta y escritor',bio:'Poeta nacido en Vallehermoso, La Gomera, una de las voces fundamentales de la literatura canaria del siglo XX.'},
{id:'jose-aguiar',name:'José Aguiar',born:1895,island:'la-gomera',category:'Artes',role:'Pintor',bio:'Pintor nacido en La Gomera, autor de una obra de gran presencia mural y figurativa.'},
{id:'juan-ismael',name:'Juan Ismael',born:1907,island:'fuerteventura',category:'Artes',role:'Pintor y poeta',bio:'Artista y poeta majorero vinculado a las vanguardias canarias del siglo XX.'},
{id:'manuel-velazquez',name:'Manuel Velázquez Cabrera',born:1863,island:'fuerteventura',category:'Política',role:'Político y abogado',bio:'Político y abogado majorero, recordado por su defensa de los intereses insulares y su papel en la historia institucional de Canarias.'},
{id:'cesar-manrique',name:'César Manrique',born:1919,island:'lanzarote',category:'Artes',role:'Artista y creador',bio:'Artista lanzaroteño cuya obra integró arte, arquitectura, paisaje y defensa del territorio.'},
{id:'pancho-lasso',name:'Pancho Lasso',born:1904,island:'lanzarote',category:'Artes',role:'Escultor',bio:'Escultor lanzaroteño vinculado a las vanguardias y a una lectura moderna de la cultura popular de las islas.'},
{id:'valentina-sabinosa',name:'Valentina Hernández “la de Sabinosa”',born:1889,island:'el-hierro',category:'Música',role:'Cantadora y referente del folclore',bio:'Figura esencial de la tradición musical herreña, cuya memoria está ligada a la transmisión del folclore de El Hierro.'}
];
const mapWrap=document.getElementById('mapWrap'),panel=document.getElementById('panel'),nodesLayer=document.getElementById('profileNodes'),network=document.getElementById('network'),legend=document.getElementById('legend');let currentIsland=null,currentCategory='Todas',currentProfile=null;
Object.entries(islands).forEach(([slug,island])=>{const b=document.createElement('button');b.className='island-hotspot';b.dataset.island=slug;b.style.left=island.x+'%';b.style.top=island.y+'%';b.innerHTML=`<span class="island-label">${island.name}</span>`;b.addEventListener('click',()=>openIsland(slug));mapWrap.appendChild(b)});
function setActiveIsland(slug){document.querySelectorAll('.island-hotspot').forEach(el=>el.classList.toggle('active',el.dataset.island===slug))}function century(y){return Math.ceil(y/100)}function decade(y){return Math.floor(y/10)*10}function roman(n){const m={1:'I',2:'II',3:'III',4:'IV',5:'V',6:'VI',7:'VII',8:'VIII',9:'IX',10:'X',11:'XI',12:'XII',13:'XIII',14:'XIV',15:'XV',16:'XVI',17:'XVII',18:'XVIII',19:'XIX',20:'XX',21:'XXI'};return m[n]||n}
function relationTags(a,b){const t=[];if(a.island===b.island)t.push({key:'island',label:'misma isla'});if(a.category===b.category)t.push({key:'category',label:'misma disciplina'});if(decade(a.born)===decade(b.born))t.push({key:'decade',label:`década de ${decade(a.born)}`});if(century(a.born)===century(b.born))t.push({key:'century',label:`siglo ${roman(century(a.born))}`});return t}function scoreRel(a,b){const t=relationTags(a,b).map(x=>x.key);return(t.includes('decade')?6:0)+(t.includes('category')?5:0)+(t.includes('island')?3:0)+(t.includes('century')?1:0)}function getConnections(p){return people.filter(x=>x.id!==p.id&&relationTags(p,x).length).sort((a,b)=>scoreRel(p,b)-scoreRel(p,a)||a.born-b.born).slice(0,14)}
function lineColor(tags){const k=tags.map(t=>t.key);if(k.includes('decade'))return'var(--same-decade)';if(k.includes('category'))return'var(--same-category)';if(k.includes('island'))return'var(--same-island)';return'var(--same-century)'}function hashOffset(str){let h=0;for(let i=0;i<str.length;i++)h=(h*31+str.charCodeAt(i))>>>0;const a=(h%360)*Math.PI/180,r=2.4+((h>>8)%28)/10;return{dx:Math.cos(a)*r,dy:Math.sin(a)*r}}function clearNetwork(){network.innerHTML='';nodesLayer.innerHTML='';legend.hidden=true}
function drawNetwork(person){clearNetwork();legend.hidden=false;const center=islands[person.island],conns=getConnections(person),positions=[];conns.forEach(p=>{const base=islands[p.island],off=hashOffset(p.id);let x=base.x+off.dx,y=base.y+off.dy;if(p.island===person.island){x=base.x+off.dx*1.8;y=base.y+off.dy*1.8}positions.push({p,x,y});const tags=relationTags(person,p),line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',center.x*10);line.setAttribute('y1',center.y*4.74);line.setAttribute('x2',x*10);line.setAttribute('y2',y*4.74);line.setAttribute('stroke',lineColor(tags));line.setAttribute('stroke-width','1.15');line.setAttribute('stroke-opacity','.58');if(tags.length===1&&tags[0].key==='century')line.setAttribute('stroke-dasharray','4 5');network.appendChild(line)});const central=document.createElement('button');central.className='profile-node central';central.style.left=center.x+'%';central.style.top=center.y+'%';central.innerHTML=`<span class="profile-dot"></span><span class="node-label">${person.name}</span>`;nodesLayer.appendChild(central);positions.forEach(({p,x,y})=>{const n=document.createElement('button');n.className='profile-node';n.style.left=x+'%';n.style.top=y+'%';n.innerHTML=`<span class="profile-dot"></span><span class="node-label">${p.name}</span>`;n.title=relationTags(person,p).map(t=>t.label).join(' · ');n.addEventListener('click',()=>openProfile(p.id));nodesLayer.appendChild(n)})}
function resetMapCopy(){document.getElementById('mapTitle').textContent='Ocho islas. Miles de historias conectadas.';document.getElementById('mapSub').textContent='Pulsa una isla para descubrir sus personas. Abre un perfil para ver cómo se conecta con el resto del archipiélago.'}
function renderHome(){currentIsland=null;currentProfile=null;setActiveIsland(null);clearNetwork();resetMapCopy();panel.innerHTML=`<div class="panel-head"><div><div class="eyebrow">Explorar</div><h2>Empieza por una isla</h2></div></div><p class="lede">El mapa es la entrada principal. Cada isla abre un directorio alfabético de personas nacidas allí.</p><div class="home-card"><strong>Demostración de la constelación</strong><p>Abre a Benito Pérez Galdós para ver relaciones generadas por isla, disciplina, década y siglo.</p><button class="primary" onclick="openProfile('benito-perez-galdos')">Abrir a Galdós →</button></div><p class="footer-note">Prototipo funcional. La base de datos completa irá creciendo con perfiles documentados y relaciones históricas verificadas.</p>`}
function openIsland(slug){currentIsland=slug;currentProfile=null;currentCategory='Todas';clearNetwork();setActiveIsland(slug);const island=islands[slug];document.getElementById('mapTitle').textContent=island.name;document.getElementById('mapSub').textContent='Personas nacidas en esta isla. Filtra por disciplina o busca por nombre.';renderIslandList()}
function renderIslandList(query=''){const island=islands[currentIsland],all=people.filter(p=>p.island===currentIsland),filtered=all.filter(p=>(currentCategory==='Todas'||p.category===currentCategory)&&p.name.toLowerCase().includes(query.toLowerCase())),cats=['Todas',...new Set(all.map(p=>p.category))],groups={};filtered.sort((a,b)=>a.name.localeCompare(b.name,'es')).forEach(p=>{const l=p.name[0].toUpperCase();(groups[l]??=[]).push(p)});panel.innerHTML=`<div class="panel-head"><div><div class="eyebrow">Isla</div><h2>${island.name}</h2><div class="count">${all.length} perfiles en este prototipo</div></div><button class="back" style="display:block" onclick="renderHome()">←</button></div><input class="search" id="search" placeholder="Buscar una persona…" value="${query.replaceAll('"','&quot;')}"/><div class="chips">${cats.map(c=>`<button class="chip ${currentCategory===c?'active':''}" data-cat="${c}">${c}</button>`).join('')}</div><div id="list">${Object.keys(groups).length?Object.entries(groups).map(([l,ps])=>`<div class="alpha-block"><div class="alpha-letter">${l}</div>${ps.map(p=>`<button class="person-row" onclick="openProfile('${p.id}')"><span><strong>${p.name}</strong><small>${p.role}</small></span><span class="year">${p.born}</span></button>`).join('')}</div>`).join(''):`<div class="empty">Todavía no hay perfiles que coincidan con este filtro.</div>`}</div><p class="footer-note">La Graciosa aparecerá desde el principio aunque al inicio tenga pocos perfiles: no vamos a inventar nombres para rellenar la base.</p>`;document.getElementById('search').addEventListener('input',e=>renderIslandList(e.target.value));document.querySelectorAll('[data-cat]').forEach(btn=>btn.addEventListener('click',()=>{currentCategory=btn.dataset.cat;renderIslandList(document.getElementById('search')?.value||'')}))}
function openProfile(id){const p=people.find(x=>x.id===id);if(!p)return;currentProfile=p;currentIsland=p.island;setActiveIsland(p.island);drawNetwork(p);document.getElementById('mapTitle').textContent=p.name;document.getElementById('mapSub').textContent='Cada línea representa al menos una relación automática dentro de la base: territorio, disciplina o tiempo.';const conns=getConnections(p);panel.innerHTML=`<div class="panel-head"><div><div class="profile-kicker">${islands[p.island].name}</div><h2 class="profile-title">${p.name}</h2></div><button class="back" style="display:block" onclick="openIsland('${p.island}')">←</button></div><div class="profile-meta">${p.born} · ${p.role}</div><p class="profile-bio">${p.bio}</p><div class="facts"><div class="fact"><b>Isla</b><span>${islands[p.island].name}</span></div><div class="fact"><b>Disciplina</b><span>${p.category}</span></div><div class="fact"><b>Década</b><span>${decade(p.born)}</span></div><div class="fact"><b>Siglo</b><span>${roman(century(p.born))}</span></div></div><div class="rel-title">Conexiones visibles · ${conns.length}</div>${conns.slice(0,8).map(c=>`<div class="rel-card" onclick="openProfile('${c.id}')"><strong>${c.name}</strong><div class="rel-tags">${relationTags(p,c).map(t=>`<span class="tag ${t.key}">${t.label}</span>`).join('')}</div></div>`).join('')}<p class="footer-note">En la versión final añadiremos relaciones documentadas —amistad, colaboración, instituciones, movimientos culturales, parentesco, maestro/discípulo— además de estas conexiones automáticas.</p>`}
document.getElementById('galdosDemo').addEventListener('click',()=>openProfile('benito-perez-galdos'));renderHome();