import {state,person,source,parents,children,partners,sortedPeople,refresh,renderPeople,renderTree,renderTasks,setPage,notify} from './workspace.js';
const $=id=>document.getElementById(id), val=id=>$(id).value.trim(),opt=id=>val(id)||null,year=id=>val(id)?Number(val(id)):null;
let client=null,editPerson=null,editSource=null,editTask=null;
function show(id){$(id).showModal();}function close(id){$(id).close();}
async function change(table,payload,id){let q=client.from('gen_'+table);const {data,error}=id?await q.update(payload).eq('id',id).select().single():await q.insert(payload).select().single();if(error)throw error;return data;}
async function erase(table,id){const {error}=await client.from('gen_'+table).delete().eq('id',id);if(error)throw error;await refresh();notify('Registro eliminado.');}
async function remove(table,id,question){if(!window.confirm(question))return;try{await erase(table,id);}catch(e){notify('Error: '+e.message,true);}}
function personForm(id=null){let p=person(id);editPerson=id;$('personForm').reset();$('personDialogTitle').textContent=p?'Editar persona':'Nueva persona';const fields={pName:'full_name',pAlias:'aliases',pSex:'sex',pBirthDate:'birth_date',pBirthYear:'birth_year',pBirthPrecision:'birth_precision',pBirthPlace:'birth_place',pDeathDate:'death_date',pDeathYear:'death_year',pDeathPrecision:'death_precision',pDeathPlace:'death_place',pBio:'biography',pNotes:'research_notes',pVerification:'verification'};for(let [element,key] of Object.entries(fields))if(p&&p[key]!=null)$(element).value=p[key];$('pLiving').value=p?.is_living===true?'true':p?.is_living===false?'false':'';show('personDialog');}
function sourceForm(id=null){let s=state.sources.find(x=>x.id===id);editSource=id;$('sourceForm').reset();$('sourceDialogTitle').textContent=s?'Editar fuente':'Nueva fuente';let fields={sTitle:'title',sType:'source_type',sDate:'source_date',sArchive:'archive_name',sReference:'reference',sUrl:'source_url',sTranscription:'transcription',sNotes:'notes'};for(let [element,key] of Object.entries(fields))if(s&&s[key]!=null)$(element).value=s[key];show('sourceDialog');}
function taskForm(id=null){let t=state.tasks.find(x=>x.id===id);editTask=id;$('taskForm').reset();$('taskDialogTitle').textContent=t?'Editar tarea':'Nueva tarea';if(t){$('tTitle').value=t.title;$('tPerson').value=t.person_id||'';$('tStatus').value=t.status;$('tPriority').value=t.priority;$('tNotes').value=t.notes;}show('taskDialog');}
function relationForm(id){$('relationForm').reset();if(id)$('rA').value=id;show('relationDialog');}
function hasDescendant(start,target){let done=new Set(),pending=[start];while(pending.length){let id=pending.pop();if(id===target)return true;if(done.has(id))continue;done.add(id);children(id).forEach(x=>pending.push(x.id));}return false;}
export function bindActions(supabase){client=supabase;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));$('headerAdd').onclick=()=>{switch(state.page){case'people':personForm();break;case'tree':relationForm(state.focus);break;case'sources':sourceForm();break;case'documents':$('docTitle').focus();break;case'tasks':taskForm();}};
$('personForm').onsubmit=async e=>{e.preventDefault();let data={full_name:val('pName'),aliases:opt('pAlias'),sex:val('pSex'),birth_date:opt('pBirthDate'),birth_year:year('pBirthYear'),birth_precision:val('pBirthPrecision'),birth_place:opt('pBirthPlace'),death_date:opt('pDeathDate'),death_year:year('pDeathYear'),death_precision:val('pDeathPrecision'),death_place:opt('pDeathPlace'),is_living:val('pLiving')===''?null:val('pLiving')==='true',biography:val('pBio'),research_notes:val('pNotes'),verification:val('pVerification')};for(let type of ['birth','death']){if(data[type+'_date']){let y=Number(data[type+'_date'].slice(0,4));if(data[type+'_year']&&data[type+'_year']!==y){notify('La fecha y el año no coinciden.',true);return;}data[type+'_year']=y;data[type+'_precision']='exact';}}if(data.birth_year&&data.death_year&&data.death_year<data.birth_year){notify('La defunción es anterior al nacimiento.',true);return;}if(data.is_living&&data.death_date){notify('Una persona viva no puede tener defunción.',true);return;}try{let row=await change('people',data,editPerson);state.selected=row.id;close('personDialog');await refresh();setPage('people');notify('Ficha guardada.');}catch(err){notify(err.message,true);}};
$('sourceForm').onsubmit=async e=>{e.preventDefault();let data={title:val('sTitle'),source_type:val('sType'),source_date:opt('sDate'),archive_name:opt('sArchive'),reference:opt('sReference'),source_url:opt('sUrl'),transcription:opt('sTranscription'),notes:val('sNotes')};try{await change('sources',data,editSource);close('sourceDialog');await refresh();notify('Fuente guardada.');}catch(err){notify(err.message,true);}};
$('taskForm').onsubmit=async e=>{e.preventDefault();let data={title:val('tTitle'),person_id:opt('tPerson'),status:val('tStatus'),priority:val('tPriority'),notes:val('tNotes')};try{await change('tasks',data,editTask);close('taskDialog');await refresh();notify('Tarea guardada.');}catch(err){notify(err.message,true);}};
$('relationForm').onsubmit=async e=>{e.preventDefault();let a=val('rA'),b=val('rB'),type=val('rType');if(!a||!b||a===b){notify('Elige dos personas diferentes.',true);return;}if(type==='parent'&&(parents(b).some(p=>p.id===a)||hasDescendant(b,a))){notify('Esta filiación ya existe o produciría un parentesco circular.',true);return;}if(type==='partner'&&partners(a).some(p=>p.id===b)){notify('Esta pareja ya figura en el árbol.',true);return;}try{await change('relations',{person_a:a,person_b:b,relation_type:type,certainty:val('rCertainty'),notes:val('rNotes')});close('relationDialog');await refresh();notify('Relación registrada.');}catch(err){notify(err.message,true);}};
$('evidenceForm').onsubmit=async e=>{e.preventDefault();let data={person_id:val('ePerson'),source_id:val('eSource'),claim:val('eClaim'),strength:val('eStrength'),notes:val('eNotes')};if(!data.person_id||!data.source_id){notify('Selecciona persona y fuente.',true);return;}try{await change('evidence',data);close('evidenceDialog');await refresh();notify('Prueba vinculada.');}catch(err){notify(err.message,true);}};
$('eventForm').onsubmit=async e=>{e.preventDefault();let data={person_id:val('evPerson'),event_type:val('evType'),event_date:opt('evDate'),event_year:year('evYear'),date_precision:val('evPrecision'),place:opt('evPlace'),source_id:opt('evSource'),description:val('evDescription')};if(data.event_date){let y=Number(data.event_date.slice(0,4));if(data.event_year&&data.event_year!==y){notify('Fecha y año no coinciden.',true);return;}data.event_year=y;data.date_precision='exact';}try{await change('events',data);close('eventDialog');await refresh();notify('Acontecimiento guardado.');}catch(err){notify(err.message,true);}};
$('uploadForm').onsubmit=async e=>{e.preventDefault();let file=$('docFile').files[0],msg=$('uploadStatus');if(!file){msg.textContent='Selecciona un archivo.';return;}let formats={'application/pdf':'pdf','image/jpeg':'jpg','image/png':'png','image/webp':'webp'},ext=formats[file.type];if(!ext||file.size>10485760){msg.textContent='Admite PDF o imágenes de hasta 10 MB.';return;}let path='documentos/'+crypto.randomUUID()+'.'+ext,btn=e.target.querySelector('button');btn.disabled=true;msg.textContent='Subiendo…';try{let uploaded=await client.storage.from('genealogia-privada').upload(path,file,{contentType:file.type,upsert:false});if(uploaded.error)throw uploaded.error;try{await change('documents',{title:val('docTitle'),object_path:path,mime_type:file.type,file_size:file.size,person_id:opt('docPerson'),source_id:opt('docSource'),notes:val('docNotes')});}catch(err){await client.storage.from('genealogia-privada').remove([path]);throw err;}$('uploadForm').reset();msg.textContent='Documento guardado en el archivo privado.';await refresh();notify('Documento incorporado.');}catch(err){msg.textContent='Error: '+err.message;notify('No se pudo subir el documento.',true);}finally{btn.disabled=false;}};
document.addEventListener('click',async e=>{let b=e.target.closest('[data-action]');if(!b)return;let id=b.dataset.id,act=b.dataset.action;switch(act){case'openPerson':state.selected=id;setPage('people');renderPeople();break;case'focusTree':state.focus=id;setPage('tree');renderTree();break;case'editPerson':personForm(id);break;case'deletePerson':await remove('people',id,'¿Eliminar esta persona junto con sus relaciones, eventos y pruebas? No se puede deshacer.');break;case'addRelation':relationForm(id);break;case'deleteRelation':await remove('relations',id,'¿Eliminar este vínculo?');break;case'addEvidence':$('evidenceForm').reset();$('ePerson').value=id;show('evidenceDialog');break;case'deleteEvidence':await remove('evidence',id,'¿Desvincular esta prueba?');break;case'addEvent':$('eventForm').reset();$('evPerson').value=id;show('eventDialog');break;case'deleteEvent':await remove('events',id,'¿Eliminar este acontecimiento?');break;case'editSource':sourceForm(id);break;case'deleteSource':await remove('sources',id,'¿Eliminar esta fuente y las pruebas que la referencian?');break;case'editTask':taskForm(id);break;case'deleteTask':await remove('tasks',id,'¿Eliminar esta tarea?');break;case'cycleTask':{let t=state.tasks.find(x=>x.id===id);if(!t)return;let next=t.status==='pending'?'in_progress':t.status==='in_progress'?'done':'pending';try{await change('tasks',{status:next},id);await refresh();notify('Estado actualizado.');}catch(err){notify(err.message,true);}break;}case'openDocument':{let doc=state.documents.find(d=>d.id===id);if(!doc)return;let tab=window.open('about:blank','_blank');let {data,error}=await client.storage.from('genealogia-privada').createSignedUrl(doc.object_path,60);if(error||!data?.signedUrl){if(tab)tab.close();notify('No se pudo abrir el archivo.',true);return;}if(tab)tab.location.href=data.signedUrl;else notify('Permite las ventanas emergentes para abrir el documento.',true);break;}case'deleteDocument':{let doc=state.documents.find(d=>d.id===id);if(!doc||!window.confirm('¿Eliminar permanentemente el archivo original?'))return;let result=await client.storage.from('genealogia-privada').remove([doc.object_path]);if(result.error){notify(result.error.message,true);return;}try{await erase('documents',id);}catch(err){notify('Archivo borrado, pero la ficha aún existe: '+err.message,true);}break;}}});}
