import { supabase as db } from '../supabase-client.js';

const islandNames={'el-hierro':'El Hierro','la-palma':'La Palma','la-gomera':'La Gomera','tenerife':'Tenerife','gran-canaria':'Gran Canaria','fuerteventura':'Fuerteventura','lanzarote':'Lanzarote','la-graciosa':'La Graciosa'};
const styleNames={isa:'Isa',folia:'Folía',malaguena:'Malagueña',seguidilla:'Seguidilla',saltona:'Saltona',polka:'Polka',berlina:'Berlina',sorondongo:'Sorondongo',tajaraste:'Tajaraste',otro:'Otro'};
let entries=[],activeType='all',activeStyle='all',activeIsland='',searchTerm='',pending=[],selectedSubmission=null;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es');
const date=v=>v?new Date(v).toLocaleDateString('es-ES',{day:'numeric',month:'short',year:'numeric'}):'';
const selected=root=>$$('.choice.on',root).map(x=>x.dataset.value);
const split=v=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean);

$$('[data-go]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.go)?.scrollIntoView({behavior:'smooth'}));
$$('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close)?.close());
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));
$$('.choice').forEach(b=>b.onclick=()=>b.classList.toggle('on'));

function corpus(e){return norm([e.text,e.entry_type,...(e.styles||[]).map(x=>styleNames[x]||x),...(e.islands||[]).map(x=>islandNames[x]||x),...(e.themes||[]),...(e.mentions||[]),e.contributor_name,islandNames[e.contributor_island]||'',e.anecdote].filter(Boolean).join(' '))}
function rows(){const q=norm(searchTerm);return entries.filter(e=>(activeType==='all'||e.entry_type===activeType)&&(activeStyle==='all'||(e.styles||[]).includes(activeStyle))&&(!activeIsland||(e.islands||[]).includes(activeIsland))&&(!q||corpus(e).includes(q)))}
function render(){const data=rows(),grid=$('#grid');$('#count').textContent=`${data.length} ${data.length===1?'resultado':'resultados'}`;const ctx=[];if(searchTerm)ctx.push(`“${searchTerm}”`);if(activeIsland)ctx.push(islandNames[activeIsland]);if(activeStyle!=='all')ctx.push(styleNames[activeStyle]);if(activeType!=='all')ctx.push(activeType==='copla'?'Coplas':'Estribillos');$('#context').textContent=ctx.join(' · ');if(!data.length){grid.innerHTML='<div class="empty"><strong>No hemos encontrado coincidencias.</strong>Prueba otra palabra o limpia los filtros.</div>';return}grid.innerHTML=data.map(e=>{const styles=(e.styles||[]).map(x=>styleNames[x]||x),islands=(e.islands||[]).map(x=>islandNames[x]||x);return `<article class="card" data-entry-id="${e.id}"><div class="tags"><span class="tag">${e.entry_type==='copla'?'Copla':'Estribillo'}</span>${styles.slice(0,4).map(s=>`<span class="tag alt">${esc(s)}</span>`).join('')}</div><p class="lyric">${esc(e.text)}</p><div class="meta">${styles.length?`<span><b>Se puede cantar como:</b> ${esc(styles.join(' · '))}</span>`:''}${islands.length?`<span><b>Relacionada con:</b> ${esc(islands.join(' · '))}</span>`:''}${e.contributor_name?`<span><b>Aportada por:</b> ${esc(e.contributor_name)}${e.contributor_island?' · '+esc(islandNames[e.contributor_island]||e.contributor_island):''}</span>`:''}${e.published_at?`<span><b>En el banco desde:</b> ${esc(date(e.published_at))}</span>`:''}</div>${e.anecdote?`<p class="anec">${esc(e.anecdote)}</p>`:''}</article>`}).join('')}
async function loadEntries(){const {data,error}=await db.from('mc_entries').select('id,text,entry_type,styles,islands,themes,mentions,contributor_name,contributor_island,anecdote,published_at').eq('status','published').order('published_at',{ascending:false});if(error){console.error(error);$('#grid').innerHTML='<div class="empty"><strong>No se pudo abrir el banco.</strong>Inténtalo de nuevo.</div>';return}entries=data||[];render()}
function sync(){$$('#types [data-type]').forEach(b=>b.classList.toggle('on',b.dataset.type===activeType));$$('#styles [data-style]').forEach(b=>b.classList.toggle('on',b.dataset.style===activeStyle));$$('.island').forEach(n=>n.classList.toggle('on',n.dataset.i===activeIsland))}
$('#types').onclick=e=>{const b=e.target.closest('[data-type]');if(!b)return;activeType=b.dataset.type;sync();render()};
$('#styles').onclick=e=>{const b=e.target.closest('[data-style]');if(!b)return;activeStyle=b.dataset.style;sync();render()};
$('#clear').onclick=()=>{activeType='all';activeStyle='all';activeIsland='';searchTerm='';$('#q').value='';$('#mapstate').textContent='Toca una isla para ver las letras relacionadas.';sync();render()};
function search(){searchTerm=$('#q').value.trim();document.getElementById('buscar').scrollIntoView({behavior:'smooth'});render()}
$('#searchBtn').onclick=search;$('#q').onkeydown=e=>{if(e.key==='Enter')search()};
$('#heroChips').onclick=e=>{const b=e.target.closest('.chip');if(!b)return;if(b.dataset.t){activeType=b.dataset.t;activeStyle='all'}if(b.dataset.s){activeStyle=b.dataset.s;activeType='all'}sync();render();document.getElementById('buscar').scrollIntoView({behavior:'smooth'})};
$$('.island').forEach(n=>{const go=()=>{activeIsland=activeIsland===n.dataset.i?'':n.dataset.i;sync();$('#mapstate').innerHTML=activeIsland?`Mostrando letras relacionadas con <b>${esc(islandNames[activeIsland])}</b>.`:'Toca una isla para ver las letras relacionadas.';render();document.getElementById('buscar').scrollIntoView({behavior:'smooth'})};n.onclick=go;n.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}}});
$('#random').onclick=()=>{const data=rows();if(!data.length)return;const e=data[Math.floor(Math.random()*data.length)];document.getElementById('buscar').scrollIntoView({behavior:'smooth'});setTimeout(()=>{const c=document.querySelector(`[data-entry-id="${e.id}"]`);if(c){c.classList.add('flash');c.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>c.classList.remove('flash'),1800)}},350)};

const contrib=$('#contrib');['#openContrib','#openContrib2','#openContrib3'].forEach(id=>$(id)?.addEventListener('click',()=>contrib.showModal()));
$('#contribForm').onsubmit=async e=>{e.preventDefault();const msg=$('#contribMsg');msg.className='msg';msg.textContent='Enviando…';if($('#websiteField').value)return;const name=$('#contributorName').value.trim();const payload={text:$('#contributionText').value.trim(),entry_type:$('#contributionType').value,styles:selected($('#contributionStyles')),islands:selected($('#contributionIslands')),themes:[],mentions:[],contributor_name:name||null,contributor_island:$('#contributorIsland').value||null,display_name_public:Boolean(name&&$('#displayNamePublic').checked),anecdote:$('#contributionAnecdote').value.trim()||null};const {error}=await db.from('mc_submissions').insert(payload);if(error){console.error(error);msg.textContent='No se pudo enviar.';return}msg.classList.add('ok');msg.textContent='Gracias. Queda pendiente de revisión.';e.target.reset();$$('.choice.on',e.target).forEach(x=>x.classList.remove('on'));setTimeout(()=>contrib.close(),1400)};

async function openAdmin(){const d=$('#admin');d.showModal();const {data:{session}}=await db.auth.getSession();if(session)await handleSession(session);else{$('#adminLogin').hidden=false;$('#adminBoard').hidden=true}}
['#adminBtn','#adminFoot'].forEach(id=>$(id)?.addEventListener('click',openAdmin));
async function handleSession(session){const {data,error}=await db.from('admin_users').select('user_id').eq('user_id',session.user.id).maybeSingle();if(error||!data){$('#adminLogin').hidden=false;$('#adminBoard').hidden=true;$('#adminLoginMsg').textContent='Este usuario no tiene acceso de administrador.';return}$('#adminLogin').hidden=true;$('#adminBoard').hidden=false;$('#adminMail').textContent=session.user.email||'';await loadPending()}
$('#adminLoginForm').onsubmit=async e=>{e.preventDefault();const m=$('#adminLoginMsg');m.textContent='Comprobando…';const {data,error}=await db.auth.signInWithPassword({email:$('#adminEmail').value.trim(),password:$('#adminPassword').value});if(error){m.textContent='No se pudo iniciar sesión.';return}m.textContent='';await handleSession(data.session)};
$('#adminLogout').onclick=async()=>{await db.auth.signOut();selectedSubmission=null;$('#adminBoard').hidden=true;$('#adminLogin').hidden=false};
async function loadPending(){const {data,error}=await db.from('mc_submissions').select('*').eq('status','pending').order('created_at',{ascending:true});if(error)return;pending=data||[];$('#pendingCount').textContent=pending.length;renderQueue();if(selectedSubmission)selectedSubmission=pending.find(x=>x.id===selectedSubmission.id)||null;if(selectedSubmission)renderEditor(selectedSubmission);else $('#editor').innerHTML='<div class="editor-empty">Selecciona una aportación para revisarla.</div>'}
function renderQueue(){$('#queueList').innerHTML=pending.length?pending.map(s=>`<button class="queueitem" data-id="${s.id}"><small>${s.entry_type}</small><strong>${esc(s.text.replace(/\n/g,' '))}</strong><span>${esc(date(s.created_at))}${s.contributor_name?' · '+esc(s.contributor_name):''}</span></button>`).join(''):'<div class="editor-empty" style="height:120px">No hay propuestas pendientes.</div>';$$('.queueitem').forEach(b=>b.onclick=()=>{selectedSubmission=pending.find(x=>x.id===b.dataset.id);renderEditor(selectedSubmission)})}
function opts(values,all,names){return all.map(v=>`<button type="button" class="choice ${values.includes(v)?'on':''}" data-value="${v}">${esc(names[v]||v)}</button>`).join('')}
function renderEditor(s){const styles=Object.keys(styleNames),islands=Object.keys(islandNames);$('#editor').innerHTML=`<p class="kicker">Revisión</p><label class="field"><span>Letra</span><textarea id="edText">${esc(s.text)}</textarea></label><div class="two"><label class="field"><span>Tipo</span><select id="edType"><option value="copla" ${s.entry_type==='copla'?'selected':''}>Copla</option><option value="estribillo" ${s.entry_type==='estribillo'?'selected':''}>Estribillo</option></select></label><label class="field"><span>Isla del colaborador</span><select id="edContributorIsland"><option value="">—</option>${islands.map(v=>`<option value="${v}" ${s.contributor_island===v?'selected':''}>${islandNames[v]}</option>`).join('')}</select></label></div><div class="field"><span>Aires compatibles</span><div class="choices" id="edStyles">${opts(s.styles||[],styles,styleNames)}</div></div><div class="field"><span>Islas relacionadas</span><div class="choices" id="edIslands">${opts(s.islands||[],islands,islandNames)}</div></div><div class="two"><label class="field"><span>Temas</span><input id="edThemes" value="${esc((s.themes||[]).join(', '))}"></label><label class="field"><span>Elementos mencionados</span><input id="edMentions" value="${esc((s.mentions||[]).join(', '))}"></label></div><label class="field"><span>Nombre del colaborador</span><input id="edName" value="${esc(s.contributor_name||'')}"></label><label class="check"><input id="edDisplayName" type="checkbox" ${s.display_name_public?'checked':''}><span>Mostrar públicamente el nombre.</span></label><label class="field"><span>Anecdotario</span><textarea id="edAnecdote">${esc(s.anecdote||'')}</textarea></label><label class="field"><span>Nota interna</span><textarea id="edAdminNote" style="min-height:70px"></textarea></label><div class="modactions"><button class="approve" id="approveSubmission">Aprobar y publicar</button><button class="duplicate" id="duplicateSubmission">Duplicada</button><button class="reject" id="rejectSubmission">Rechazar</button><span class="msg" id="moderationMessage"></span></div>`;$$('#edStyles .choice,#edIslands .choice').forEach(b=>b.onclick=()=>b.classList.toggle('on'));$('#approveSubmission').onclick=approve;$('#duplicateSubmission').onclick=()=>moderate('duplicate');$('#rejectSubmission').onclick=()=>moderate('rejected')}
function editorPayload(){return {p_submission_id:selectedSubmission.id,p_text:$('#edText').value.trim(),p_entry_type:$('#edType').value,p_styles:selected($('#edStyles')),p_islands:selected($('#edIslands')),p_themes:split($('#edThemes').value).slice(0,12),p_mentions:split($('#edMentions').value).slice(0,20),p_contributor_name:$('#edName').value.trim()||null,p_contributor_island:$('#edContributorIsland').value||null,p_display_name_public:$('#edDisplayName').checked,p_anecdote:$('#edAnecdote').value.trim()||null,p_admin_note:$('#edAdminNote').value.trim()||null}}
async function approve(){const m=$('#moderationMessage');m.textContent='Publicando…';const {error}=await db.rpc('mc_approve_submission',editorPayload());if(error){console.error(error);m.textContent='No se pudo publicar.';return}selectedSubmission=null;await Promise.all([loadPending(),loadEntries()])}
async function moderate(status){const {error}=await db.rpc('mc_moderate_submission',{p_submission_id:selectedSubmission.id,p_status:status,p_admin_note:$('#edAdminNote').value.trim()||null});if(error)return;selectedSubmission=null;await loadPending()}

const legal={legal:{title:'Aviso legal',html:'<p>Este Aviso Legal regula el acceso y uso del <strong>Banco de Memoria Cantada de Canarias</strong>, un proyecto cultural de DE8 Films dentro de EL ALCE PROMOCIONAL S.L.U.</p><div class="legalbox"><h3>Titular</h3><p><strong>EL ALCE PROMOCIONAL S.L.U</strong> · NIF B76741099<br>Calle Isaac Peral nº 3, Nave 2B, CP 38109, El Rosario, Santa Cruz de Tenerife, España.<br>922 199 152 · gerencia@elalce.info</p></div><h2>Aportaciones comunitarias</h2><p>Las propuestas quedan sometidas a moderación editorial antes de publicarse.</p><h2>Clasificación territorial</h2><p>La relación con una isla indica únicamente que la letra menciona, evoca o se dedica a elementos vinculados con ese territorio. No supone atribución de origen ni de autoría.</p>'},privacy:{title:'Política de privacidad',html:'<p>El formulario permite enviar una letra, clasificaciones, nombre opcional, isla opcional y anecdotario. El nombre solo se muestra públicamente si la persona colaboradora lo autoriza expresamente.</p><div class="legalbox"><h3>Responsable</h3><p><strong>EL ALCE PROMOCIONAL S.L.U</strong> · NIF B76741099 · gerencia@elalce.info · 922 199 152.</p></div><h2>Finalidad</h2><p>Los datos se utilizan para recibir, revisar, ordenar y, cuando proceda, publicar las aportaciones y mantener la trazabilidad editorial del archivo.</p>'},cookies:{title:'Política de cookies',html:'<p>La versión actual no incorpora cookies propias con fines publicitarios, de elaboración de perfiles o de analítica comercial.</p><h2>Tecnologías necesarias</h2><p>El acceso privado de administración puede utilizar almacenamiento técnico para mantener una sesión autenticada. Supabase presta los servicios de datos y autenticación y Google Fonts sirve Work Sans.</p>'}};
$$('[data-legal]').forEach(b=>b.onclick=()=>{const x=legal[b.dataset.legal];$('#legalTitle').textContent=x.title;$('#legalBody').innerHTML=x.html;$('#legalDialog').showModal()});
loadEntries();
