import {supabase} from '../../../supabase-client.js';
const $=id=>document.getElementById(id);
const people=new Map();let relations=[],focus=null,selected=null,canvas={width:900,height:600},scale=1,tx=0,ty=0,busy=false,initialized=false;
const W=210,H=100,DX=246,DY=164;
const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=p=>{let a=p.birth_year||(p.birth_date||'').slice(0,4)||'?',b=p.death_year||(p.death_date||'').slice(0,4)||(p.is_living===true?'actualidad':'?');return `${p.birth_precision==='approximate'?'c. ':''}${a} – ${p.death_precision==='approximate'?'c. ':''}${b}`;};
function graph(){const neighbors=new Map([...people.keys()].map(id=>[id,[]]));for(const r of relations){if(!neighbors.has(r.person_a)||!neighbors.has(r.person_b))continue;neighbors.get(r.person_a).push({id:r.person_b,delta:r.relation_type==='parent'?1:0});neighbors.get(r.person_b).push({id:r.person_a,delta:r.relation_type==='parent'?-1:0});}return neighbors;}
function components(adj){const seen=new Set(),sets=[];const starts=[focus,...people.keys()].filter(Boolean);for(const start of starts){if(seen.has(start)||!adj.has(start))continue;const ids=[],queue=[start];seen.add(start);for(let i=0;i<queue.length;i++){const id=queue[i];ids.push(id);for(const edge of adj.get(id)){if(!seen.has(edge.id)){seen.add(edge.id);queue.push(edge.id);}}}sets.push(ids);}return sets;}
function compute(){const adj=graph(),sets=components(adj);const layouts=[];let width=850;for(const ids of sets){const set=new Set(ids),anchor=set.has(focus)?focus:[...ids].sort((a,b)=>(people.get(a).birth_year||9999)-(people.get(b).birth_year||9999))[0];const ranks=new Map([[anchor,0]]),queue=[anchor];for(let i=0;i<queue.length;i++){const id=queue[i];for(const e of adj.get(id)){if(set.has(e.id)&&!ranks.has(e.id)){ranks.set(e.id,ranks.get(id)+e.delta);queue.push(e.id);}}}const min=Math.min(...ranks.values()),rows=new Map();for(const id of ids){const rank=ranks.get(id)-min;if(!rows.has(rank))rows.set(rank,[]);rows.get(rank).push(id);}const rankList=[...rows.keys()].sort((a,b)=>a-b);for(const rank of rankList){rows.get(rank).sort((a,b)=>{const pa=people.get(a),pb=people.get(b);return (pa.birth_date||String(pa.birth_year||9999)).localeCompare(pb.birth_date||String(pb.birth_year||9999))||pa.full_name.localeCompare(pb.full_name,'es');});}const cols=Math.max(...[...rows.values()].map(row=>row.length)),cw=Math.max(690,cols*DX+66);width=Math.max(width,cw);layouts.push({ids,rows,rankList,cw,levels:Math.max(...rankList)+1});}
const nodes=new Map();let top=96;const headings=[];for(const part of layouts){headings.push({text:part===layouts[0]?'Árbol familiar completo':`Rama sin conexión registrada · ${people.get(part.ids[0]).full_name}`,y:top-54});for(const rank of part.rankList){const list=part.rows.get(rank),rowWidth=(list.length-1)*DX+W;const start=(width-rowWidth)/2;list.forEach((id,i)=>nodes.set(id,{id,x:start+i*DX,y:top+rank*DY,rank}));}top+=part.levels*DY+88;}
const edges=relations.filter(r=>nodes.has(r.person_a)&&nodes.has(r.person_b));return {nodes,edges,width,height:Math.max(540,top+20),headings,parts:layouts.length};}
function pathFor(a,b,rel){if(rel.relation_type==='partner'){const ax=a.x+W/2,ay=a.y+H/2,bx=b.x+W/2,by=b.y+H/2;return `M ${ax} ${ay} L ${bx} ${by}`;}const parent=a,child=b;const ax=parent.x+W/2,ay=parent.y+H,bx=child.x+W/2,by=child.y;const mid=(ay+by)/2;return by>ay?`M ${ax} ${ay} V ${mid} H ${bx} V ${by}`:`M ${ax} ${parent.y+H/2} L ${bx} ${child.y+H/2}`;}
function setTransform(){$('stage').style.transform=`translate(${tx}px,${ty}px) scale(${scale})`;$('zoomLabel').textContent=`${Math.round(scale*100)} %`;}
function fit(){const box=$('viewport');if(!box.clientWidth||!canvas.width)return;scale=Math.min(1.2,(box.clientWidth-38)/canvas.width,(box.clientHeight-40)/canvas.height);scale=Math.max(.015,scale);tx=(box.clientWidth-canvas.width*scale)/2;ty=(box.clientHeight-canvas.height*scale)/2;setTransform();}
function zoom(factor,cx=$('viewport').clientWidth/2,cy=$('viewport').clientHeight/2){const old=scale;scale=Math.min(3,Math.max(.015,scale*factor));tx=cx-(cx-tx)*scale/old;ty=cy-(cy-ty)*scale/old;setTransform();}
function panel(id){selected=id;const p=people.get(id);const box=$('details');if(!p){box.hidden=true;return;}box.hidden=false;$('detailName').textContent=p.full_name;$('detailYears').textContent=label(p);$('detailPlaces').textContent=[p.birth_place,p.death_place].filter(Boolean).join(' · ')||'Lugares pendientes';$('detailStatus').textContent=p.verification==='documented'?'Documentado':p.verification==='family'?'Información familiar':p.verification==='conflict'?'Contradicción':'Pendiente de verificar';$('detailProfile').href=`../../?person=${encodeURIComponent(p.id)}`;document.querySelectorAll('.tree-node').forEach(b=>b.classList.toggle('selected',b.dataset.id===id));}
function render(){const model=compute();canvas={width:model.width,height:model.height};$('stage').style.width=`${model.width}px`;$('stage').style.height=`${model.height}px`;$('connections').setAttribute('width',model.width);$('connections').setAttribute('height',model.height);$('connections').setAttribute('viewBox',`0 0 ${model.width} ${model.height}`);$('connections').replaceChildren();$('cards').replaceChildren();for(const edge of model.edges){const a=model.nodes.get(edge.person_a),b=model.nodes.get(edge.person_b);const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',pathFor(a,b,edge));path.setAttribute('fill','none');path.setAttribute('stroke',edge.relation_type==='partner'?'#ae8650':'#8e877e');path.setAttribute('stroke-width','2');if(['pending','probable','contradictory','conflict'].includes(edge.certainty))path.setAttribute('stroke-dasharray','6 5');$('connections').append(path);}for(const heading of model.headings){const el=document.createElement('div');el.className='branch-heading';el.style.top=`${heading.y}px`;el.textContent=heading.text;$('cards').append(el);}for(const n of model.nodes.values()){const p=people.get(n.id),b=document.createElement('button');b.type='button';b.className='tree-node'+(n.id===focus?' focus':'')+(n.id===selected?' selected':'')+((p.birth_precision==='approximate'||p.death_precision==='approximate')?' uncertain':'');b.dataset.id=n.id;b.style.left=`${n.x}px`;b.style.top=`${n.y}px`;const strong=document.createElement('strong'),small=document.createElement('small'),em=document.createElement('em');strong.textContent=p.full_name;small.textContent=label(p);em.textContent=p.verification==='documented'?'Documentado':p.verification==='family'?'Información familiar':'Pendiente de verificar';b.append(strong,small,em);b.onclick=()=>panel(n.id);$('cards').append(b);}$('count').textContent=`${model.nodes.size} personas · ${model.edges.length} vínculos · ${model.parts} ${model.parts===1?'rama':'ramas'}`;$('status').textContent='Todas las personas están incluidas, incluso aquellas sin vínculos registrados. Pulsa una tarjeta para abrir su ficha.';if(selected&&people.has(selected))panel(selected);fit();}
function init(){if(initialized)return;initialized=true;const view=$('viewport');let drag=null;view.addEventListener('pointerdown',e=>{if(e.target.closest('button')||e.button!==0)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,tx,ty};view.setPointerCapture(e.pointerId);view.classList.add('dragging');});view.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;tx=drag.tx+e.clientX-drag.x;ty=drag.ty+e.clientY-drag.y;setTransform();});const end=e=>{if(drag?.id===e.pointerId){drag=null;view.classList.remove('dragging');}};view.addEventListener('pointerup',end);view.addEventListener('pointercancel',end);view.addEventListener('wheel',e=>{e.preventDefault();const rect=view.getBoundingClientRect();zoom(e.deltaY<0?1.2:.83,e.clientX-rect.left,e.clientY-rect.top);},{passive:false});$('fit').onclick=fit;$('zoomFit').onclick=fit;$('zoomIn').onclick=()=>zoom(1.25);$('zoomOut').onclick=()=>zoom(.8);$('focus').onchange=e=>{focus=e.target.value;render();};$('closeDetails').onclick=()=>{$('details').hidden=true;};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if($('viewer').requestFullscreen)await $('viewer').requestFullscreen();else $('status').textContent='Tu navegador no admite pantalla completa.';}catch{$('status').textContent='No se pudo activar la pantalla completa.';}};document.addEventListener('fullscreenchange',fit);new ResizeObserver(()=>{if(!$('app').hidden)fit();}).observe(view);$('logout').onclick=async()=>{await supabase.auth.signOut();people.clear();relations=[];focus=selected=null;$('app').hidden=true;$('gate').hidden=false;};}
async function check(session){if(!session?.user){$('app').hidden=true;$('gate').hidden=false;return;}if(busy)return;busy=true;try{const {data,error}=await supabase.rpc('gen_is_admin');if(error||data!==true)throw new Error('Esta cuenta no tiene acceso al archivo.');const results=await Promise.all([supabase.from('gen_people').select('*'),supabase.from('gen_relations').select('*')]);for(const r of results)if(r.error)throw r.error;people.clear();for(const p of results[0].data||[])people.set(p.id,p);relations=results[1].data||[];const sorted=[...people.values()].sort((a,b)=>a.full_name.localeCompare(b.full_name,'es'));$('focus').innerHTML=sorted.map(p=>`<option value="${escapeHTML(p.id)}">${escapeHTML(p.full_name)}</option>`).join('');const requested=new URLSearchParams(location.search).get('person');focus=people.has(requested)?requested:people.has(focus)?focus:sorted.find(p=>p.full_name==='Enrique Rodríguez Darias')?.id||sorted[0]?.id||null;selected=focus;$('gate').hidden=true;$('app').hidden=false;init();if(focus)render();else $('status').textContent='Todavía no se han añadido personas.';}catch(e){console.error(e);$('gate').hidden=false;$('app').hidden=true;$('loginStatus').textContent=e.message||'No se pudo cargar el archivo.';}finally{busy=false;}}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();const btn=$('loginButton');btn.disabled=true;$('loginStatus').textContent='Comprobando acceso…';try{const input=$('username').value.trim();const email=input==='28081988'?'info@enriquerodda.com':input;const {data,error}=await supabase.auth.signInWithPassword({email,password:$('password').value});if(error||!data?.session){$('loginStatus').textContent='Usuario o contraseña incorrectos.';return;}$('password').value='';$('loginStatus').textContent='';await check(data.session);}catch{$('loginStatus').textContent='No se pudo conectar.';}finally{btn.disabled=false;}});
supabase.auth.onAuthStateChange((_e,session)=>queueMicrotask(()=>check(session)));
const {data}=await supabase.auth.getSession();await check(data.session);
